language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t blamzilla/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true blamzilla/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-app"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-848024017678"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY